name: search_engine
description: A text engine for inserting/deleting text content, and a search engine.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  path: ^1.8.0
  http: ^0.13.0
  dart_bones: "^1.1.1"
  #  path: ../../dart/dart_bones

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
    #mockito: ^4.1.4
  #test_coverage: ^0.5.0
#  dev_dependencies:
#  pedantic: ^1.9.0
#  test: ^1.14.4
